spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:8081/short_url
    username: postgres
    password: postgres123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
